apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    app: test-secret
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-secret
  template:
    metadata:
      name: myapp
      labels:
        app: test-secret
    spec:
    # We define a volume as kind secret to map our secrets on it
      volumes:
        - name: appconfig
          secret:
            secretName: app1
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["/bin/bash"]
        args: ["-c", "while true; do sleep 5; done"]
        volumeMounts:
          - name: appconfig
            mountPath: /etc/appconfig
        resources:
          limits:
            cpu: "52m"
            memory: "128Mi"
  