apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    app: test-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-secret
  template:
    metadata:
      name: myapp
      labels:
        app: test-secret
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["/bin/bash"]
        args: ["-c", "while true; do sleep 5; done"]
        envFrom:
        - secretRef:
            name: app1
        resources:
          limits:
            cpu: "52m"
            memory: "128Mi"
  