apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hello-world-ds
spec:
  selector: 
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      # We can choose a subset of nodes based on labels to run on.
      nodeSelector:
        node: hello-world-ns
      containers:
        - name: hello-world
          image: gcr.io/hello-minikube-zero-install/hello-node