apiVersion: v1
kind: Pod
metadata:
  name: test-probes
spec: 
  containers: 
  - name: nginx
    image: nginx
  livenessProbe:
    tcpSocket:
      port:8080
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:
    tcpSocket:
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
