---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: mysite
  spec: 
    replicas: 2
    template:
      metadata:
        labels:
          app: mynginx
      spec:
        containers:
          - name: front-end
            image: suaveyosi/mynginx
            ports:
              - containerPort: 80
