apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-vars
  labels:
    app: test-vars
spec:
  selector:
    matchLabels:
      app: test-vars
  template:
    metadata:
      name: nginx-test-vars
      labels:
        app: test-vars
    spec:
      containers:
      - name: test-vars
        image: suaveyosi/testvars:latest
      ports:
        containerPort: 80
      env:
        PORT: 80
        CONTENT: "Este es un deploy desde k8s"
      command:
        - echo "${CONTENT}" > /usr/share/nginx/html/index.html
        - sleep 10